server:
  port: 9090
spring:
  rsocket:
    server:
      port: 9595
      transport: tcp
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
---
spring.thymeleaf.cache: false
---




